### ISSUE TITLE
REST API do GitHub

### ISSUE THREAD

**Issue by AguiarIsaac** [AguiarIsaac/github-blog#3]
Começando a usar o GitHub CLI
O GitHub CLI é a maneira mais fácil de usar a API Do GitHub REST da linha de comando

Instale o GitHub CLI se ainda não o instalou. Para obter instruções de instalação, consulte o [repositório GitHub CLI](https://github.com/cli/cli#installation).

Use o subcomand para autenticar no GitHub CLI. Para obter mais informações, consulte a [documentação de login do GitHub CLI](https://cli.github.com/manual/gh_auth_login).auth login

```
gh auth login
```

Use o subcomand para fazer sua solicitação de API. Para obter mais informações, consulte a [documentação do GitHub CLI api](https://cli.github.com/manual/gh_api).api

```
gh api repos/octocat/Spoon-Knife/issues
```

## Usando o GitHub CLI em ações do GitHub
Você também pode usar o GitHub CLI em seus fluxos de trabalho do GitHub Actions. Para obter mais informações, consulte "[Usando o GitHub CLI em fluxos de trabalho](https://docs.github.com/pt/actions/using-workflows/using-github-cli-in-workflows)".

Em vez de usar o comando, passe um token de acesso como uma variável de ambiente chamada . O GitHub recomenda que você use o embutido em vez de criar um token. Se isso não for possível, armazene seu token como um segredo e substitua no exemplo abaixo o nome do seu segredo. Para obter mais informações sobre , consulte "[Autenticação automática de tokens](https://docs.github.com/pt/actions/security-guides/automatic-token-authentication)". Para obter mais informações sobre segredos, consulte "[Segredos criptografados](https://docs.github.com/pt/actions/security-guides/encrypted-secrets)".gh auth loginGH_TOKENGITHUB_TOKENGITHUB_TOKENGITHUB_TOKEN

```
on:
  workflow_dispatch:
jobs:
  use_api:
    runs-on: ubuntu-latest
    permissions:
      issues: read
    steps:
      - env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api repos/octocat/Spoon-Knife/issues
```
